/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

class StrGenPluginTest {
    @Test fun `plugin registers task`() {
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.strgen")

        assertNotNull(project.tasks.findByName("generateStrGen"))
    }
}
